version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: stayhub-postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-stayhub}
      POSTGRES_USER: ${DB_USERNAME:-stayhub}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-stayhub_password}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-stayhub} -d ${DB_NAME:-stayhub}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - stayhub-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: stayhub-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qg
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - stayhub-network

  redis:
    image: redis:7-alpine
    container_name: stayhub-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - stayhub-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: stayhub-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@stayhub.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin_password}
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - stayhub-network


volumes:
  postgres_data:
    name: stayhub_postgres_data
  pgadmin_data:
    name: stayhub_pgadmin_data
  kafka_data:
    name: stayhub_kafka_data
  redis_data:
    name: stayhub_redis_data

networks:
  stayhub-network:
    name: stayhub-network
    driver: bridge
